#    description: Learn how to launch and grow your project.
#  exclude:
#    - CNAME
#    - CONTRIBUTING.md
#    - Gemfile*
#    - package.json
#    - Rakefile
#    - script
#    - vendor
#      permalink: "/:path/"
#  collections:
#      output: true
#  
#    - scope:
#    - values:
#    - scope:
#    - layout: article
#    -  plugins:
#    - jekyll-seo-tag
#  
sass:
  sass_dir: assets/css/
  style: compressed
  load_paths:
    - node_modules

logo: /assets/images/cards/default.png

github:
  repository_nwo: github/opensource.guide

twitter:
  username: github

facebook:
  publisher: https://www.facebook.com/GitHub/
